"""add_section_id_to_devices

Revision ID: 00e4da358ca5
Revises: 2363852feb51
Create Date: 2026-05-04 02:01:14.013239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e4da358ca5'
down_revision: Union[str, Sequence[str], None] = '2363852feb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_enrollment_student_section', 'enrollments', ['student_id', 'section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrollment_student_section', 'enrollments', type_='unique')
    # ### end Alembic commands ###
