"""add_section_id_to_devices

Revision ID: 2363852feb51
Revises: c4c2d8f5b6a1
Create Date: 2026-05-04 01:56:35.202536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2363852feb51'
down_revision: Union[str, Sequence[str], None] = 'c4c2d8f5b6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_enrollment_student_section', 'enrollments', ['student_id', 'section_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrollment_student_section', 'enrollments', type_='unique')
    # ### end Alembic commands ###
